### ISSUE TITLE
Release Checklist for 0.0.1-beta

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/pydatastructs#427]
#### Description of the problem

Following things are to be completed for releasing 0.0.1-beta of PyDataStructs,

- [ ] Update version number everywhere.
- [ ] Update `index.rst` (installation command)
- [ ] Update `README.md` (installation command)

**Comment by czgdp1807** [comment]
N.B. https://github.com/codezonediitj/pydatastructs/pull/483#issuecomment-1073236368
